peckadesign/PublicAccessModule#1 Přenesení z projektu
peckadesign/PublicAccessModule pull request #2
Opened 2018-04-17 08:12 UTC by mhucik

2018-04-17 08:14 UTC, mhucik commented
- Upřímně si moc nejsem jistý nadefinováním těch závislostí.
 - Dále jsem tam nechal namespace začínající `App`, místo `Pd`. Tak nevím, jestli s tím nemáte nějaký problém.

2018-04-17 08:41 UTC, jankaderabek commented on README.md
> +Start with `\App\PublicAccess\PublicAccess` interface implementation.
Možná bych sem hodil jenom nějakou poznámku, že ten User reperzentuje ty data, která se zakódují do toho tokenu.

2018-04-17 08:41 UTC, jankaderabek commented on composer.json
> +			"App\\PublicAccess\\": "src/"
Ten Namespace bych upravil na nějaký vlastní, asi po vzoru ostatních balíčků `"Pd\\PdpBar\\": "src/"`

2018-04-17 09:57 UTC, klobinoid requested changes
drobnosti

2018-04-17 09:57 UTC, klobinoid commented on README.md
> +```neon
ten neon funguje? pokud ne, tak bych  dal yaml

2018-04-17 09:57 UTC, klobinoid commented on composer.json
> +	"license": "proprietary",
když to máme v public repu, tak proprietary asi nebude úplně to pravý vořechový :trollface:

2018-04-17 09:57 UTC, klobinoid commented on composer.json
> +			"App\\PublicAccess\\": "src/"
Jsem taky pro `Pd` root

2018-04-17 10:00 UTC, klobinoid commented
`Upřímně si moc nejsem jistý nadefinováním těch závislostí.` - myslíš composer závislostí?

2018-04-17 10:01 UTC, mhucik commented
Ano, composerových závislostí

2018-04-17 10:05 UTC, klobinoid commented
mě přijdou v pořádku, `nette\di` i `nette\utils` jsou použity. jen zkontroluj jestli je minimální verze kompatibilní s naším základem

2018-04-17 13:08 UTC, mhucik commented on README.md
> +```neon
když on tam udělá takové to škaredé červené odsazení

2018-04-17 13:45 UTC, mhucik commented
Připomínky zapracovány.

2018-04-23 07:05 UTC, klobinoid approved these changes

2018-04-23 07:06 UTC, klobinoid commented
squashni to a udělej release, dík

2018-04-24 11:17 UTC, merged

2018-04-24 11:20 UTC, mhucik commented
Realease vydán, děkuji.